# Generated by Django 4.2.7 on 2025-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descripcion_realizada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tiempo_empleado',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo empleado en minutos', null=True),
        ),
    ]
