# Generated by Django 4.2.7 on 2025-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_descripcion_realizada_task_tiempo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_confirmed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
